### ISSUE TITLE
Installation of multilevelmod fails

### ISSUE THREAD

**Issue by sitendug** [tidymodels/multilevelmod#27]
Installing package into ‘/home/sitendu/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘multilevelmod’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘multilevelmod’:
 .onLoad failed in loadNamespace() for 'multilevelmod', details:
  call: parsnip::set_dependency("linear_reg", eng = "stan_glmer", pkg = "rstanarm", 
  error: unused argument ("linear_reg")
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/sitendu/R/x86_64-pc-linux-gnu-library/4.1/multilevelmod’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpBw23P0/file1b0224081035/multilevelmod_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by topepo** [comment]
Do you have parsnip installed? If so, what version?

**Comment by sitendug** [comment]
Hi! Thanks for the reply, I updated the parsnip  using the devtools::install_github()and then tried installing multilevelmod, and  voila it works! Thank you so much for helping out! My Parsnip version is 0.2.0.9.

**Comment by juliasilge** [comment]
That's great to hear @sitendug! 🙌 There have been related parsnip and multilevelmod releases to CRAN and it sounds like you caught it just in the wrong situation.
