### ISSUE TITLE
Are multinom_reg() models supported?

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/multilevelmod#51]
Hi,

The "Get Started" vignette says: "For brevity, we only discuss linear models but the syntax also works for binomial, **multinomial**, and Poisson outcomes." but I am not sure if it is actually supported. After installing `multilevelmod` and the dependencies for the supported engines, the only engines available are:
``` r
library(multilevelmod)
#> Loading required package: parsnip
show_engines('multinom_reg')
#> # A tibble: 5 × 2
#>   engine mode          
#>   <chr>  <chr>         
#> 1 glmnet classification
#> 2 spark  classification
#> 3 keras  classification
#> 4 nnet   classification
#> 5 brulee classification
```

Also, `multinom_reg()` isn't listed as a supported engine in the README. Just wanted to make sure I wasn't missing something.

**Comment by jpiaskowski** [comment]
nnet supports multinomial outcomes

**Comment by mattwarkentin** [comment]
But does it support multi-level multinomial...?

**Comment by hfrick** [comment]
Good catch! I think you're right and there are no engines for `multinomial_reg()` in `multilevelmod`. I'll update the vignette accordingly. 

Did you have particular engines in mind that you would have expected to see?

@topepo is this an indication of previous plans to support multinomial responses?

**Comment by mattwarkentin** [comment]
Umm, I don't have an engine in mind. I was pointing a friend toward this packed for MLM, but he was interested in multinomial regression so I wanted to check in and clarify. Not sure if there are existing packages to scaffold onto.
