### ISSUE TITLE
Logistic_reg() not working with stan-glmer

### ISSUE THREAD

**Issue by euriconoleto** [tidymodels/multilevelmod#8]
Thanks for the great package!

When trying to use logistic regression as suggested, it returns an error “Error: engine ‘stan-glmer’ is not available.

```r
library(multilevelmod)
hier_model_spec <- logistic_reg() %>% set_engine("stan-glmer")
```

**Comment by juliasilge** [comment]
Looks like [we only have the `"gee"` engine for `logistic_reg()` that ever got set up](https://github.com/tidymodels/multilevelmod/blob/8ccd3226f674f2db30a39a99b676e6dcd8e300fa/R/logistic_reg_data.R).

``` r
library(multilevelmod)
#> Loading required package: parsnip

logistic_reg() %>% set_engine("lmer")
#> Error: Engine 'lmer' is not available. Please use one of: 'glm', 'glmnet', 'LiblineaR', 'spark', 'keras', 'stan'
logistic_reg() %>% set_engine("stan-glmer")
#> Error: Engine 'stan-glmer' is not available. Please use one of: 'glm', 'glmnet', 'LiblineaR', 'spark', 'keras', 'stan'
```

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
